/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 14 21:30:53 GMT 2026
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.IOException;
import java.io.PipedWriter;
import java.nio.BufferOverflowException;
import java.nio.ByteBuffer;
import java.nio.CharBuffer;
import java.nio.ReadOnlyBufferException;
import java.nio.charset.Charset;
import org.apache.commons.cli.help.FilterHelpAppendable;
import org.apache.commons.cli.help.TextHelpAppendable;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class FilterHelpAppendable_ESTest extends FilterHelpAppendable_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      TextHelpAppendable textHelpAppendable1 = (TextHelpAppendable)textHelpAppendable0.append((CharSequence) "F4LFf~nY:F3@7MZ_{", 7, 7);
      assertEquals(7, TextHelpAppendable.DEFAULT_LIST_INDENT);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      char[] charArray0 = new char[0];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      TextHelpAppendable textHelpAppendable1 = (TextHelpAppendable)textHelpAppendable0.append((CharSequence) charBuffer0);
      assertEquals(1, textHelpAppendable1.getLeftPad());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      char[] charArray0 = new char[5];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0, 0, 0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charBuffer1);
      // Undeclared exception!
      try { 
        textHelpAppendable0.append((CharSequence) charBuffer1, 0, 0);
        fail("Expecting exception: ReadOnlyBufferException");
      
      } catch(ReadOnlyBufferException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.CharBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      // Undeclared exception!
      try { 
        textHelpAppendable0.append((CharSequence) "}Y'%t2", (-3015), (-1128));
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.FilterHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      CharBuffer charBuffer0 = CharBuffer.allocate(4808);
      // Undeclared exception!
      try { 
        textHelpAppendable0.append((CharSequence) charBuffer0, (-1), (-1));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.HeapCharBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      PipedWriter pipedWriter0 = new PipedWriter();
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(pipedWriter0);
      try { 
        textHelpAppendable0.append((CharSequence) "F(K>nw", 1, 1);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Pipe not connected
         //
         verifyException("java.io.PipedWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      CharBuffer charBuffer0 = CharBuffer.wrap((CharSequence) "", 0, 0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charBuffer0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.append((CharSequence) charBuffer0);
        fail("Expecting exception: ReadOnlyBufferException");
      
      } catch(ReadOnlyBufferException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.CharBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      char[] charArray0 = new char[9];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charBuffer0);
      Charset charset0 = Charset.defaultCharset();
      ByteBuffer byteBuffer0 = ByteBuffer.allocateDirect(39);
      CharBuffer charBuffer1 = charset0.decode(byteBuffer0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.append((CharSequence) charBuffer1);
        fail("Expecting exception: BufferOverflowException");
      
      } catch(BufferOverflowException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.CharBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      PipedWriter pipedWriter0 = new PipedWriter();
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(pipedWriter0);
      char[] charArray0 = new char[0];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      try { 
        textHelpAppendable0.append((CharSequence) charBuffer0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Pipe not connected
         //
         verifyException("java.io.PipedWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      char[] charArray0 = new char[8];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      CharBuffer charBuffer1 = CharBuffer.wrap((CharSequence) charBuffer0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charBuffer1);
      // Undeclared exception!
      try { 
        textHelpAppendable0.append('c');
        fail("Expecting exception: ReadOnlyBufferException");
      
      } catch(ReadOnlyBufferException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.StringCharBuffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CharBuffer charBuffer0 = CharBuffer.allocate(0);
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(charBuffer0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.append('B');
        fail("Expecting exception: BufferOverflowException");
      
      } catch(BufferOverflowException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("java.nio.Buffer", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      // Undeclared exception!
      try { 
        textHelpAppendable0.append('o');
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.FilterHelpAppendable", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      PipedWriter pipedWriter0 = new PipedWriter();
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable(pipedWriter0);
      try { 
        textHelpAppendable0.append('a');
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Pipe not connected
         //
         verifyException("java.io.PipedWriter", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      FilterHelpAppendable filterHelpAppendable0 = textHelpAppendable0.append('\u0010');
      assertSame(textHelpAppendable0, filterHelpAppendable0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = TextHelpAppendable.systemOut();
      // Undeclared exception!
      try { 
        textHelpAppendable0.append((CharSequence) "TextStyle{LEFT, l:0, i:0, true, min:0, max:unset}", 0, Integer.MAX_VALUE);
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TextHelpAppendable textHelpAppendable0 = new TextHelpAppendable((Appendable) null);
      Charset charset0 = Charset.defaultCharset();
      ByteBuffer byteBuffer0 = charset0.encode("G|G%<7");
      CharBuffer charBuffer0 = charset0.decode(byteBuffer0);
      // Undeclared exception!
      try { 
        textHelpAppendable0.append((CharSequence) charBuffer0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.help.FilterHelpAppendable", e);
      }
  }
}
