/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 14 21:06:18 GMT 2026
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.cli.Converter;
import org.apache.commons.cli.DeprecatedAttributes;
import org.apache.commons.cli.Option;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Option_ESTest extends Option_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      Option option0 = new Option("9", "9", false, (String) null);
      option0.setArgs((-1259));
      boolean boolean0 = option0.requiresArg();
      assertEquals((-1259), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      Option option0 = new Option("B", true, "h");
      String string0 = option0.getValue("");
      assertFalse(option0.hasLongOpt());
      assertEquals("h", option0.getDescription());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      Option option0 = new Option("XF", false, "XF");
      option0.setOptionalArg(true);
      option0.setArgs(0);
      assertTrue(option0.hasOptionalArg());
      
      option0.processValue("@");
      assertFalse(option0.hasArgs());
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.valueSeparator();
      option_Builder0.option("b");
      Option option0 = option_Builder0.get();
      option0.setArgs(46);
      option0.processValue("J1=\"!W=qD{V`)");
      assertEquals(46, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      Option option0 = new Option("9", "9", false, (String) null);
      option0.isValuesEmpty();
      assertTrue(option0.hasLongOpt());
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      option0.processValue("iIc");
      boolean boolean0 = option0.isValuesEmpty();
      assertFalse(boolean0);
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.required(true);
      Option.Builder option_Builder1 = option_Builder0.longOpt("+f9");
      Option option0 = option_Builder1.get();
      boolean boolean0 = option0.isRequired();
      assertTrue(boolean0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, true, (String) null);
      option0.setOptionalArg(true);
      boolean boolean0 = option0.hasOptionalArg();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.option("b");
      option_Builder0.optionalArg(true);
      Option option0 = option_Builder0.get();
      option0.processValue("b");
      option0.getValuesList();
      assertEquals(1, option0.getArgs());
      assertFalse(option0.hasValueSeparator());
      assertTrue(option0.hasOptionalArg());
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("?V");
      option_Builder0.valueSeparator('3');
      Option option0 = option_Builder0.get();
      char char0 = option0.getValueSeparator();
      assertEquals('3', char0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.valueSeparator('F');
      option_Builder0.longOpt("2i4!nHx");
      Option option0 = option_Builder0.get();
      char char0 = option0.getValueSeparator();
      assertEquals((-1), option0.getArgs());
      assertEquals('F', char0);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      Option option0 = new Option("B", true, "h");
      option0.processValue("");
      String string0 = option0.getValue("J9<{m(zpr vRSr");
      assertFalse(option0.hasLongOpt());
      assertEquals("", string0);
      assertEquals("h", option0.getDescription());
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.option("?V");
      option_Builder1.hasArg(true);
      Option option0 = option_Builder0.get();
      assertTrue(option0.hasArg());
      
      option0.processValue("?V");
      String string0 = option0.getValue(0);
      assertFalse(option0.hasValueSeparator());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      Option option0 = new Option("XF", false, "XF");
      option0.setArgs(12);
      option0.processValue("7'C");
      option0.getValue();
      assertEquals(12, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("%7");
      Option.Builder option_Builder1 = option_Builder0.since("%7");
      Option option0 = option_Builder1.get();
      option0.getSince();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("2i4!nHx");
      Option option0 = option_Builder0.get();
      option0.getOpt();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.getLongOpt();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      Option option0 = new Option("9D$", "xi#U", false, "PWSe");
      String string0 = option0.getLongOpt();
      assertEquals("xi#U", string0);
      assertEquals("PWSe", option0.getDescription());
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("");
      Option option0 = option_Builder0.get();
      option0.getKey();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      Option option0 = new Option("9", "9", false, (String) null);
      String string0 = option0.getDescription();
      assertEquals((-1), option0.getArgs());
      assertTrue(option0.hasLongOpt());
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      Option option0 = new Option("B", true, "h");
      assertEquals("h", option0.getDescription());
      
      option0.setDescription("");
      option0.getDescription();
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      option_Builder0.deprecated(deprecatedAttributes0);
      option_Builder0.longOpt("+f9");
      Option option0 = option_Builder0.get();
      option0.getDeprecated();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      Option option0 = new Option("XF", false, "XF");
      assertEquals((-1), option0.getArgs());
      
      option0.setArgs(0);
      int int0 = option0.getArgs();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      Option option0 = new Option("6", "6", true, "6");
      int int0 = option0.getArgs();
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("+f9");
      option_Builder0.argName("uD}H`ZHOfIqe$S3HPG");
      Option option0 = option_Builder0.get();
      option0.getArgName();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      Option option0 = new Option("9", "9", true, (String) null);
      option0.setArgName("");
      option0.getArgName();
      assertTrue(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("?V");
      option_Builder0.hasArg(true);
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.acceptsArg();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      // Undeclared exception!
      try { 
        option0.processValue((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // value
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      option0.processValue("iIc");
      try { 
        option0.getValue(2);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 2, Size: 1
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, true, (String) null);
      // Undeclared exception!
      try { 
        option0.getId();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      // Undeclared exception!
      try { 
        Option.builder("xi#U");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The option 'xi#U' contains an illegal character : '#'.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      Option option0 = null;
      try {
        option0 = new Option("", false, "");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Empty option name.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      Option option0 = null;
      try {
        option0 = new Option("Cannot add value, list full.", "", false, "[ ");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The option 'Cannot add value, list full.' contains an illegal character : ' '.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      Option option0 = null;
      try {
        option0 = new Option("org.apache.commons.cli.OptionValidator", "The addValue method is not intended for client use. Subclasses should use the processValue method instead.");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The option 'org.apache.commons.cli.OptionValidator' contains an illegal character : '.'.
         //
         verifyException("org.apache.commons.cli.OptionValidator", e);
      }
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      Option option0 = new Option("9D$", "xi#U", false, "PWSe");
      option0.isDeprecated();
      assertEquals("PWSe", option0.getDescription());
      assertEquals("xi#U", option0.getLongOpt());
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      option_Builder0.deprecated(deprecatedAttributes0);
      option_Builder0.longOpt("+f9");
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.isDeprecated();
      assertTrue(boolean0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      Option option0 = new Option((String) null, "", true, (String) null);
      boolean boolean0 = option0.hasValueSeparator();
      assertFalse(boolean0);
      assertTrue(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      Option option0 = new Option((String) null, "l`", false, "l`");
      option0.setValueSeparator('%');
      boolean boolean0 = option0.hasValueSeparator();
      assertEquals('%', option0.getValueSeparator());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      Option option0 = new Option("9", "9", false, (String) null);
      boolean boolean0 = option0.hasArgs();
      assertEquals((-1), option0.getArgs());
      assertFalse(boolean0);
      assertTrue(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      Option option0 = new Option("B", true, "h");
      option0.setArgs(115);
      boolean boolean0 = option0.hasArgs();
      assertEquals(115, option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, true, (String) null);
      option0.setArgs((-2));
      boolean boolean0 = option0.hasArgs();
      assertEquals((-2), option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("value");
      option_Builder1.hasArgs();
      Option option0 = option_Builder1.get();
      boolean boolean0 = option0.hasArg();
      assertTrue(boolean0);
      assertTrue(option0.hasArgs());
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.hasArg(true);
      option_Builder0.longOpt("2i4!nHx");
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.hasArg();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      Option option0 = new Option((String) null, false, (String) null);
      boolean boolean0 = option0.hasArg();
      assertFalse(boolean0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      Option option0 = new Option("B", true, "h");
      option0.processValue("");
      String string0 = option0.getValue();
      assertNotNull(string0);
      assertFalse(option0.hasLongOpt());
      assertEquals("h", option0.getDescription());
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      Option option0 = new Option("$", "$", false, "$");
      option0.getKey();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, true, (String) null);
      String string0 = option0.getKey();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("2i4!nHx");
      Option option0 = option_Builder0.get();
      option0.getValueSeparator();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null, true, (String) null);
      boolean boolean0 = option0.hasOptionalArg();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.option("?V");
      option_Builder0.deprecated();
      Option option0 = option_Builder0.get();
      String string0 = option0.toString();
      assertEquals((-1), option0.getArgs());
      assertEquals("[ Option ?V Deprecated :: null :: class java.lang.String ]", string0);
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.longOpt("");
      Option.Builder option_Builder1 = option_Builder0.deprecated();
      Option option0 = option_Builder1.get();
      String string0 = option0.toDeprecatedString();
      assertEquals((-1), option0.getArgs());
      assertEquals("Option 'null''': Deprecated", string0);
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      String string0 = option0.toDeprecatedString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      Option option0 = new Option("B", true, "B");
      option0.processValue("B");
      option0.setArgs((-2));
      boolean boolean0 = option0.requiresArg();
      assertTrue(option0.hasArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      Option option0 = new Option("B", true, "B");
      option0.setArgs((-2));
      boolean boolean0 = option0.requiresArg();
      assertTrue(option0.hasArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.optionalArg(true);
      Option.Builder option_Builder2 = option_Builder1.longOpt("");
      Option option0 = option_Builder2.get();
      boolean boolean0 = option0.requiresArg();
      assertEquals(1, option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.option("b");
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.requiresArg();
      assertFalse(boolean0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.valueSeparator();
      option_Builder1.option("b");
      option_Builder1.numberOfArgs((-975));
      Option option0 = option_Builder0.get();
      // Undeclared exception!
      try { 
        option0.processValue("JmN=\"!W=qD{V`)");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot add value, list full.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.valueSeparator();
      option_Builder1.optionalArg(true);
      option_Builder1.option("b");
      Option option0 = option_Builder0.get();
      option0.processValue("J1=\"!W=qD{V`)");
      assertTrue(option0.hasValueSeparator());
      assertEquals('=', option0.getValueSeparator());
      assertEquals(1, option0.getArgs());
      assertTrue(option0.hasOptionalArg());
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      Option option0 = new Option("@", false, "@");
      // Undeclared exception!
      try { 
        option0.processValue("\"(ij&*AH=Ww");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // NO_ARGS_ALLOWED
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.option("?V");
      option_Builder0.deprecated();
      Option option0 = option_Builder0.get();
      String string0 = option0.toDeprecatedString();
      assertEquals((-1), option0.getArgs());
      assertEquals("Option '?V': Deprecated", string0);
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      Option option0 = new Option("p", "p", true, "p");
      boolean boolean0 = option0.hasLongOpt();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      Option option0 = new Option("9", "9");
      boolean boolean0 = option0.hasLongOpt();
      assertFalse(boolean0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      Option option0 = new Option("B", true, "B");
      option0.setArgs((-2));
      option0.toString();
      assertEquals((-2), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.option("b");
      Option option0 = option_Builder0.get();
      option0.setArgName("b");
      boolean boolean0 = option0.hasArgName();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      Option option0 = new Option("B", true, "B");
      boolean boolean0 = option0.hasArgName();
      assertFalse(option0.hasLongOpt());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.option("?V");
      option_Builder1.hasArgs();
      Option option0 = option_Builder0.get();
      option0.processValue("[ Option ?V Deprecated[ARG...] :: null :: class java.lang.String ]");
      assertFalse(option0.hasValueSeparator());
      assertTrue(option0.hasArg());
      assertEquals((-2), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.option("b");
      Option option0 = option_Builder0.get();
      String[] stringArray0 = option0.getValues();
      assertNull(stringArray0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      option0.processValue("[ Option null [ARG] :: null :: class java.lang.String ]");
      String[] stringArray0 = option0.getValues();
      assertNotNull(stringArray0);
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      Option option0 = new Option((String) null, (String) null);
      option0.getValue((String) null);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.option("b");
      Option option0 = option_Builder0.get();
      option0.getValue((-1));
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.option("b");
      option_Builder0.optionalArg(true);
      Option option0 = option_Builder0.get();
      option0.processValue("b");
      try { 
        option0.getValue((-989));
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      String string0 = option0.getValue();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      Option option0 = new Option("B", true, "B");
      option0.processValue("B");
      String string0 = option0.getValue("[ Option B B[ARG...] :: B :: class java.lang.String ]");
      assertEquals("B", string0);
      assertFalse(option0.hasValueSeparator());
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.option("b");
      Option option0 = option_Builder0.get();
      option0.getId();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      Option option0 = new Option("@", "@", false, "@");
      Option option1 = new Option("@", "@", true, "@");
      boolean boolean0 = option0.equals(option1);
      assertTrue(boolean0);
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      Option option0 = new Option("@", false, "@");
      Option option1 = new Option("@", "@", false, "@");
      boolean boolean0 = option1.equals(option0);
      assertFalse(boolean0);
      assertEquals((-1), option1.getArgs());
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.option("b");
      Option option0 = option_Builder0.get();
      Option option1 = new Option((String) null, "J1=\"!W=qD{V`)");
      boolean boolean0 = option0.equals(option1);
      assertEquals((-1), option0.getArgs());
      assertFalse(boolean0);
      assertEquals((-1), option1.getArgs());
      assertFalse(option1.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.option("b");
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.equals(option0);
      assertEquals((-1), option0.getArgs());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.option("b");
      Option option0 = option_Builder0.get();
      boolean boolean0 = option0.equals((Object) null);
      assertEquals((-1), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      assertTrue(option0.hasArg());
      
      option0.processValue("[ Option null [ARG] :: null :: class java.lang.String ]");
      boolean boolean0 = option0.acceptsArg();
      assertFalse(boolean0);
      assertFalse(option0.hasValueSeparator());
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.optionalArg(true);
      Option.Builder option_Builder1 = option_Builder0.optionalArg(true);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.optionalArg(false);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.hasArg(false);
      assertSame(option_Builder0, option_Builder1);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      option0.setType((Object) null);
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      Option option0 = new Option("B", true, "B");
      assertFalse(option0.hasLongOpt());
      
      option0.setLongOpt("B");
      String string0 = option0.toString();
      assertEquals("[ Option B B [ARG] :: B :: class java.lang.String ]", string0);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      Option option0 = new Option("9D$", "xi#U", false, "PWSe");
      String string0 = option0.getOpt();
      assertEquals((-1), option0.getArgs());
      assertEquals("9D$", string0);
      assertEquals("PWSe", option0.getDescription());
      assertEquals("xi#U", option0.getLongOpt());
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.option("?V");
      Option option0 = option_Builder0.get();
      option0.getType();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.option("b");
      Option option0 = option_Builder0.get();
      // Undeclared exception!
      try { 
        option0.addValue("b");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // The addValue method is not intended for client use. Subclasses should use the processValue method instead.
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      Option option0 = new Option((String) null, "", true, (String) null);
      String string0 = option0.getLongOpt();
      assertEquals(1, option0.getArgs());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      Option option0 = new Option((String) null, "", true, (String) null);
      option0.hashCode();
      assertTrue(option0.hasLongOpt());
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      Option option0 = new Option("p", "p", true, "p");
      option0.isRequired();
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      Option option0 = new Option("p", "p", true, "p");
      option0.getSince();
      assertEquals(1, option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      Option option0 = new Option("B", true, "B");
      String string0 = option0.getDescription();
      assertFalse(option0.hasLongOpt());
      assertNotNull(string0);
      assertTrue(option0.hasArg());
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      Option option0 = new Option("@", false, "@");
      int int0 = option0.getArgs();
      assertEquals((-1), int0);
      assertFalse(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      Option option0 = new Option("9D$", "xi#U", false, "PWSe");
      option0.clearValues();
      assertEquals("PWSe", option0.getDescription());
      assertEquals((-1), option0.getArgs());
      assertEquals(57, option0.getId());
      assertEquals("xi#U", option0.getLongOpt());
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      Option option0 = new Option((String) null, "", true, (String) null);
      option0.getDeprecated();
      assertEquals(1, option0.getArgs());
      assertTrue(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.option("b");
      Option option0 = option_Builder0.get();
      option0.setArgName("");
      boolean boolean0 = option0.hasArgName();
      assertEquals((-1), option0.getArgs());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      Option option0 = new Option("p", "p", true, "p");
      Option option1 = (Option)option0.clone();
      assertNotSame(option1, option0);
      assertEquals(1, option1.getArgs());
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      Option option0 = new Option((String) null, "", true, (String) null);
      // Undeclared exception!
      try { 
        option0.getId();
        fail("Expecting exception: StringIndexOutOfBoundsException");
      
      } catch(StringIndexOutOfBoundsException e) {
      }
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      option_Builder0.option("b");
      Option option0 = option_Builder0.get();
      option0.getValuesList();
      assertEquals((-1), option0.getArgs());
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      Option option0 = new Option((String) null, "", true, (String) null);
      option0.getArgName();
      assertTrue(option0.hasArg());
      assertTrue(option0.hasLongOpt());
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      Option option0 = new Option((String) null, true, (String) null);
      Object object0 = new Object();
      // Undeclared exception!
      try { 
        option0.setType(object0);
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.Object cannot be cast to java.lang.Class
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.hasArgs();
      Option.Builder option_Builder2 = option_Builder1.optionalArg(true);
      assertSame(option_Builder0, option_Builder2);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("9D$");
      Option.Builder option_Builder1 = option_Builder0.desc("Not yet implemented");
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.hasArg();
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Converter<String, Exception> converter0 = (Converter<String, Exception>) mock(Converter.class, new ViolatedAssumptionAnswer());
      Option.Builder option_Builder1 = option_Builder0.converter(converter0);
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder("9D$");
      Option.Builder option_Builder1 = option_Builder0.required();
      assertSame(option_Builder1, option_Builder0);
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      Option.Builder option_Builder1 = option_Builder0.longOpt("");
      Option option0 = option_Builder1.get();
      option0.setRequired(true);
      assertTrue(option0.isRequired());
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        option_Builder0.get();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }
}
