/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 14 21:33:42 GMT 2026
 */

package org.apache.commons.cli.help;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.PriorityQueue;
import java.util.Stack;
import java.util.TreeSet;
import java.util.Vector;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.example.WeirdOptionFormat;
import org.apache.commons.cli.help.TableDefinition;
import org.apache.commons.cli.help.TextStyle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TableDefinition_ESTest extends TableDefinition_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>();
      Stack<String> stack0 = new Stack<String>();
      TableDefinition tableDefinition0 = TableDefinition.from("Whg_<gLKeL/,", arrayList0, stack0, (Iterable<List<String>>) null);
      Iterable<List<String>> iterable0 = tableDefinition0.rows();
      assertNull(iterable0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TreeSet<TextStyle> treeSet0 = new TreeSet<TextStyle>();
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>(treeSet0);
      LinkedHashSet<List<String>> linkedHashSet0 = new LinkedHashSet<List<String>>(261);
      TableDefinition tableDefinition0 = TableDefinition.from("", linkedList0, (List<String>) null, linkedHashSet0);
      List<String> list0 = tableDefinition0.headers();
      assertNull(list0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ArrayList<String> arrayList0 = new ArrayList<String>();
      TableDefinition tableDefinition0 = TableDefinition.from("", (List<TextStyle>) null, arrayList0, (Iterable<List<String>>) null);
      List<String> list0 = tableDefinition0.headers();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      Vector<String> vector0 = new Vector<String>();
      vector0.add("org.apache.commons.cli.help.TableDefinition$1");
      TableDefinition tableDefinition0 = TableDefinition.from("k", linkedList0, vector0, (Iterable<List<String>>) null);
      List<String> list0 = tableDefinition0.headers();
      assertTrue(list0.contains("org.apache.commons.cli.help.TableDefinition$1"));
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      TreeSet<Option> treeSet0 = new TreeSet<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) treeSet0);
      List<String> list0 = tableDefinition0.headers();
      LinkedList<List<String>> linkedList0 = new LinkedList<List<String>>();
      ArrayDeque<List<String>> arrayDeque0 = new ArrayDeque<List<String>>(linkedList0);
      TableDefinition tableDefinition1 = TableDefinition.from("bc", (List<TextStyle>) null, list0, arrayDeque0);
      List<TextStyle> list1 = tableDefinition1.columnTextStyles();
      assertNull(list1);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ArrayList<TextStyle> arrayList0 = new ArrayList<TextStyle>();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      LinkedHashSet<List<String>> linkedHashSet0 = new LinkedHashSet<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from("", arrayList0, linkedList0, linkedHashSet0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      LinkedList<String> linkedList1 = new LinkedList<String>();
      PriorityQueue<List<String>> priorityQueue0 = new PriorityQueue<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from((String) null, linkedList0, linkedList1, priorityQueue0);
      String string0 = tableDefinition0.caption();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      LinkedList<TextStyle> linkedList0 = new LinkedList<TextStyle>();
      TreeSet<List<String>> treeSet0 = new TreeSet<List<String>>();
      TableDefinition tableDefinition0 = TableDefinition.from("$", linkedList0, (List<String>) null, treeSet0);
      String string0 = tableDefinition0.caption();
      assertEquals("$", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Stack<Option> stack0 = new Stack<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) stack0);
      Iterable<List<String>> iterable0 = tableDefinition0.rows();
      assertNotNull(iterable0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Stack<Option> stack0 = new Stack<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) stack0);
      String string0 = tableDefinition0.caption();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      WeirdOptionFormat weirdOptionFormat0 = new WeirdOptionFormat();
      Stack<Option> stack0 = new Stack<Option>();
      TableDefinition tableDefinition0 = weirdOptionFormat0.apply((Iterable<Option>) stack0);
      List<TextStyle> list0 = tableDefinition0.columnTextStyles();
      assertFalse(list0.isEmpty());
  }
}
