/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat Mar 14 21:33:42 GMT 2026
 */

package org.apache.commons.cli.help;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class TableDefinition_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.commons.cli.help.TableDefinition"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/jx/mmlj34wd62vbjkzchbls8tgw0000gn/T/"); 
    java.lang.System.setProperty("user.country", "CA"); 
    java.lang.System.setProperty("user.dir", "/Users/kietvandang/Projects/EECS4313/commons-cli"); 
    java.lang.System.setProperty("user.home", "/Users/kietvandang"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "kietvandang"); 
    java.lang.System.setProperty("user.timezone", "America/Toronto"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(TableDefinition_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.commons.io.LineIterator",
      "org.apache.commons.io.input.QueueInputStream",
      "org.apache.commons.io.build.AbstractSupplier",
      "org.apache.commons.io.function.Uncheck",
      "org.apache.commons.lang3.StringUtils",
      "org.apache.commons.io.file.CountingPathVisitor$AbstractBuilder",
      "org.apache.commons.io.function.IOLongSupplier",
      "org.apache.commons.io.output.AppendableWriter",
      "org.apache.commons.io.filefilter.NotFileFilter",
      "org.apache.commons.io.filefilter.TrueFileFilter",
      "org.apache.commons.io.filefilter.AgeFileFilter",
      "org.apache.commons.io.file.SimplePathVisitor$AbstractBuilder",
      "org.apache.commons.io.function.IOQuadFunction",
      "org.apache.commons.io.output.ByteArrayOutputStream",
      "org.apache.commons.io.filefilter.ConditionalFileFilter",
      "org.apache.commons.text.similarity.EditDistance",
      "org.apache.commons.io.function.IOTriFunction",
      "org.apache.commons.io.file.Counters$Counter",
      "org.apache.commons.io.IOUtils",
      "org.apache.commons.io.filefilter.SuffixFileFilter",
      "org.apache.commons.io.file.StandardDeleteOption",
      "org.apache.commons.text.similarity.LongestCommonSubsequence",
      "org.apache.commons.io.file.AccumulatorPathVisitor$Builder",
      "org.apache.commons.io.file.Counters$LongPathCounters",
      "org.apache.commons.text.similarity.SimilarityScore",
      "org.apache.commons.text.similarity.ObjectSimilarityScore",
      "org.apache.commons.io.file.Counters$LongCounter",
      "org.apache.commons.io.function.IOBiConsumer",
      "org.apache.commons.io.filefilter.DelegateFileFilter",
      "org.apache.commons.io.function.IOBooleanSupplier",
      "org.apache.commons.io.filefilter.AndFileFilter",
      "org.apache.commons.cli.help.Util",
      "org.apache.commons.io.file.Counters$NoopPathCounters",
      "org.apache.commons.io.function.IOComparator",
      "org.apache.commons.io.file.SimplePathVisitor",
      "org.apache.commons.io.input.CharSequenceReader",
      "org.apache.commons.cli.help.TextStyle$Alignment",
      "org.apache.commons.io.CloseableURLConnection",
      "org.apache.commons.io.output.UnsynchronizedByteArrayOutputStream",
      "org.apache.commons.cli.help.TextStyle",
      "org.apache.commons.io.output.StringBuilderWriter",
      "org.apache.commons.io.filefilter.NameFileFilter",
      "org.apache.commons.io.file.DeleteOption",
      "org.apache.commons.cli.Option",
      "org.apache.commons.io.file.AccumulatorPathVisitor",
      "org.apache.commons.io.file.PathVisitor",
      "org.apache.commons.text.similarity.SimilarityInput",
      "org.apache.commons.io.FileUtils",
      "org.apache.commons.io.function.IOIntSupplier",
      "org.apache.commons.cli.help.TableDefinition",
      "org.apache.commons.cli.help.TableDefinition$1",
      "org.apache.commons.io.filefilter.SymbolicLinkFileFilter",
      "org.apache.commons.io.output.NullOutputStream",
      "org.apache.commons.cli.example.WeirdOptionFormat",
      "org.apache.commons.io.filefilter.IOFileFilter",
      "org.apache.commons.io.function.IOPredicate",
      "org.apache.commons.io.filefilter.MagicNumberFileFilter",
      "org.apache.commons.io.input.BoundedInputStream",
      "org.apache.commons.io.output.NullWriter",
      "org.apache.commons.io.file.Counters$BigIntegerPathCounters",
      "org.apache.commons.io.function.IOTriConsumer",
      "org.apache.commons.io.file.Counters$AbstractPathCounters",
      "org.apache.commons.cli.Converter",
      "org.apache.commons.io.StandardLineSeparator",
      "org.apache.commons.cli.help.TextStyle$1",
      "org.apache.commons.io.function.IOBiFunction",
      "org.apache.commons.io.file.Counters$BigIntegerCounter",
      "org.apache.commons.cli.DeprecatedAttributes",
      "org.apache.commons.io.output.AbstractByteArrayOutputStream",
      "org.apache.commons.io.filefilter.AbstractFileFilter",
      "org.apache.commons.io.output.QueueOutputStream",
      "org.apache.commons.io.function.IORunnable",
      "org.apache.commons.io.function.IOSupplier",
      "org.apache.commons.io.file.CountingPathVisitor",
      "org.apache.commons.io.FileExistsException",
      "org.apache.commons.io.filefilter.PathVisitorFileFilter",
      "org.apache.commons.io.IOExceptionList",
      "org.apache.commons.io.function.IOConsumer",
      "org.apache.commons.io.file.DeletingPathVisitor",
      "org.apache.commons.io.file.PathFilter",
      "org.apache.commons.io.filefilter.CanReadFileFilter",
      "org.apache.commons.io.filefilter.PathEqualsFileFilter",
      "org.apache.commons.io.IOCase",
      "org.apache.commons.text.similarity.HammingDistance",
      "org.apache.commons.io.function.IOIntConsumer",
      "org.apache.commons.io.function.IOFunction",
      "org.apache.commons.io.filefilter.SizeFileFilter",
      "org.apache.commons.io.filefilter.OrFileFilter",
      "org.apache.commons.io.filefilter.RegexFileFilter",
      "org.apache.commons.io.file.Counters",
      "org.apache.commons.io.file.Counters$NoopCounter",
      "org.apache.commons.io.file.CountingPathVisitor$Builder",
      "org.apache.commons.cli.Option$Builder",
      "org.apache.commons.cli.help.TextStyle$Builder",
      "org.apache.commons.io.filefilter.PrefixFileFilter",
      "org.apache.commons.io.file.Counters$PathCounters",
      "org.apache.commons.io.file.PathUtils",
      "org.apache.commons.io.input.ProxyInputStream",
      "org.apache.commons.io.file.NoopPathVisitor",
      "org.apache.commons.io.filefilter.CanWriteFileFilter"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(TableDefinition_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.commons.cli.help.TableDefinition$1",
      "org.apache.commons.cli.example.WeirdOptionFormat",
      "org.apache.commons.cli.help.TextStyle$Builder",
      "org.apache.commons.cli.help.TextStyle$Alignment",
      "org.apache.commons.cli.help.TextStyle",
      "org.apache.commons.text.similarity.LongestCommonSubsequence",
      "org.apache.commons.cli.Option",
      "org.apache.commons.lang3.StringUtils",
      "org.apache.commons.cli.help.TextStyle$1",
      "org.apache.commons.cli.help.Util",
      "org.apache.commons.io.filefilter.IOFileFilter",
      "org.apache.commons.io.filefilter.AbstractFileFilter",
      "org.apache.commons.io.filefilter.AgeFileFilter",
      "org.apache.commons.io.filefilter.NotFileFilter",
      "org.apache.commons.io.filefilter.CanWriteFileFilter",
      "org.apache.commons.io.filefilter.AndFileFilter",
      "org.apache.commons.io.filefilter.CanReadFileFilter",
      "org.apache.commons.io.file.PathUtils",
      "org.apache.commons.io.filefilter.SizeFileFilter",
      "org.apache.commons.io.file.SimplePathVisitor",
      "org.apache.commons.io.file.NoopPathVisitor",
      "org.apache.commons.text.similarity.HammingDistance",
      "org.apache.commons.io.file.CountingPathVisitor",
      "org.apache.commons.io.file.AccumulatorPathVisitor",
      "org.apache.commons.io.build.AbstractSupplier",
      "org.apache.commons.io.file.SimplePathVisitor$AbstractBuilder",
      "org.apache.commons.io.file.CountingPathVisitor$AbstractBuilder",
      "org.apache.commons.io.file.AccumulatorPathVisitor$Builder",
      "org.apache.commons.io.file.Counters",
      "org.apache.commons.io.file.Counters$AbstractPathCounters",
      "org.apache.commons.io.file.Counters$LongPathCounters",
      "org.apache.commons.io.file.Counters$LongCounter",
      "org.apache.commons.io.filefilter.SymbolicLinkFileFilter",
      "org.apache.commons.io.filefilter.TrueFileFilter",
      "org.apache.commons.io.file.Counters$BigIntegerPathCounters",
      "org.apache.commons.io.file.Counters$BigIntegerCounter",
      "org.apache.commons.io.filefilter.RegexFileFilter",
      "org.apache.commons.io.filefilter.SuffixFileFilter",
      "org.apache.commons.io.filefilter.DelegateFileFilter",
      "org.apache.commons.io.filefilter.PrefixFileFilter",
      "org.apache.commons.io.FileUtils",
      "org.apache.commons.io.function.Uncheck",
      "org.apache.commons.io.file.DeletingPathVisitor",
      "org.apache.commons.io.file.CountingPathVisitor$Builder",
      "org.apache.commons.io.file.StandardDeleteOption",
      "org.apache.commons.io.StandardLineSeparator",
      "org.apache.commons.io.IOUtils",
      "org.apache.commons.io.filefilter.PathEqualsFileFilter",
      "org.apache.commons.io.filefilter.NameFileFilter",
      "org.apache.commons.io.filefilter.PathVisitorFileFilter",
      "org.apache.commons.io.filefilter.OrFileFilter",
      "org.apache.commons.io.filefilter.MagicNumberFileFilter"
    );
  }
}
