/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 14 21:10:20 GMT 2026
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.time.format.TextStyle;
import java.util.Iterator;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.Properties;
import java.util.function.Consumer;
import java.util.function.Supplier;
import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.DeprecatedAttributes;
import org.apache.commons.cli.Option;
import org.apache.commons.cli.OptionGroup;
import org.apache.commons.text.TextStringBuilder;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CommandLine_ESTest extends CommandLine_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test000()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Object object0 = commandLine0.getParsedOptionValue("-W6?`n[UC]m6(", (Object) commandLine_Builder0);
      assertSame(object0, commandLine_Builder0);
  }

  @Test(timeout = 4000)
  public void test001()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option((String) null, "q1qaiFh2lMLq", false, "q1qaiFh2lMLq");
      optionGroup0.setSelected(option0);
      commandLine_Builder0.addOption(option0);
      boolean boolean0 = commandLine0.hasOption(optionGroup0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test002()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("initialBuffer", "L!ok");
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder1.get();
      boolean boolean0 = commandLine0.hasOption("initialBuffer");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test003()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      Locale.FilteringMode[] locale_FilteringModeArray0 = new Locale.FilteringMode[5];
      Locale.FilteringMode[] locale_FilteringModeArray1 = commandLine0.getParsedOptionValues(optionGroup0, locale_FilteringModeArray0);
      assertEquals(5, locale_FilteringModeArray1.length);
  }

  @Test(timeout = 4000)
  public void test004()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Integer[] integerArray0 = new Integer[0];
      Integer[] integerArray1 = commandLine0.getParsedOptionValues(optionGroup0, integerArray0);
      assertSame(integerArray0, integerArray1);
  }

  @Test(timeout = 4000)
  public void test005()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option((String) null, "q1qaiFh2lMLq");
      Option[] optionArray0 = commandLine0.getParsedOptionValues(option0, (Option[]) null);
      assertNull(optionArray0);
  }

  @Test(timeout = 4000)
  public void test006()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option((String) null, false, "org.apache.commons.cli.CommandLine$1");
      Option[] optionArray0 = new Option[0];
      Option[] optionArray1 = commandLine0.getParsedOptionValues(option0, optionArray0);
      assertSame(optionArray0, optionArray1);
  }

  @Test(timeout = 4000)
  public void test007()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object[] objectArray0 = commandLine0.getParsedOptionValues("c}x9>v#|7pZL`4O4", (Object[]) null);
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test008()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object[] objectArray0 = new Object[0];
      Object[] objectArray1 = commandLine0.getParsedOptionValues("CF ~F[SwK@KK^`", objectArray0);
      assertSame(objectArray1, objectArray0);
  }

  @Test(timeout = 4000)
  public void test009()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option[] optionArray0 = new Option[4];
      Supplier<Option[]> supplier0 = (Supplier<Option[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(optionArray0).when(supplier0).get();
      Option[] optionArray1 = commandLine0.getParsedOptionValues((String) null, (Supplier<Option[]>) supplier0);
      assertSame(optionArray0, optionArray1);
  }

  @Test(timeout = 4000)
  public void test010()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = new String[0];
      Supplier<String[]> supplier0 = (Supplier<String[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(supplier0).get();
      String[] stringArray1 = commandLine0.getParsedOptionValues("", (Supplier<String[]>) supplier0);
      assertEquals(0, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test011()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("r_", "r_", true, "r_");
      option0.processValue("r_");
      commandLine0.addOption(option0);
      String[] stringArray0 = commandLine0.getParsedOptionValues("r_");
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test012()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Integer[] integerArray0 = new Integer[3];
      Integer[] integerArray1 = commandLine0.getParsedOptionValues('!', integerArray0);
      assertEquals(3, integerArray1.length);
  }

  @Test(timeout = 4000)
  public void test013()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object[] objectArray0 = new Object[0];
      Object[] objectArray1 = commandLine0.getParsedOptionValues('~', objectArray0);
      assertSame(objectArray1, objectArray0);
  }

  @Test(timeout = 4000)
  public void test014()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Locale.FilteringMode[] locale_FilteringModeArray0 = new Locale.FilteringMode[15];
      Supplier<Locale.FilteringMode[]> supplier0 = (Supplier<Locale.FilteringMode[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(locale_FilteringModeArray0).when(supplier0).get();
      Locale.FilteringMode[] locale_FilteringModeArray1 = commandLine0.getParsedOptionValues('T', (Supplier<Locale.FilteringMode[]>) supplier0);
      assertSame(locale_FilteringModeArray1, locale_FilteringModeArray0);
  }

  @Test(timeout = 4000)
  public void test015()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object[] objectArray0 = new Object[0];
      Supplier<Object[]> supplier0 = (Supplier<Object[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(objectArray0).when(supplier0).get();
      Object[] objectArray1 = commandLine0.getParsedOptionValues('h', (Supplier<Object[]>) supplier0);
      assertSame(objectArray0, objectArray1);
  }

  @Test(timeout = 4000)
  public void test016()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Supplier<Object> supplier0 = (Supplier<Object>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Object object0 = commandLine0.getParsedOptionValue(optionGroup0, supplier0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test017()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      LinkedList<Option> linkedList0 = new LinkedList<Option>();
      LinkedList<Option> linkedList1 = commandLine0.getParsedOptionValue((OptionGroup) null, linkedList0);
      assertEquals(0, linkedList1.size());
  }

  @Test(timeout = 4000)
  public void test018()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("os", true, "os");
      Supplier<Integer> supplier0 = (Supplier<Integer>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Integer integer0 = commandLine0.getParsedOptionValue(option0, (Supplier<Integer>) supplier0);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test019()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option option0 = new Option((String) null, "q1qaiFh2lMLq");
      Object object0 = commandLine0.getParsedOptionValue(option0, (Object) null);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test020()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("r_", "r_", true, "r_");
      option0.processValue("org.apache.commons.cli.Option$1");
      commandLine0.addOption(option0);
      Object object0 = commandLine0.getParsedOptionValue(option0);
      assertEquals("org.apache.commons.cli.Option$1", object0);
  }

  @Test(timeout = 4000)
  public void test021()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<Locale.FilteringMode> supplier0 = (Supplier<Locale.FilteringMode>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      commandLine0.getParsedOptionValue("T", (Supplier<Locale.FilteringMode>) supplier0);
  }

  @Test(timeout = 4000)
  public void test022()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<Object> supplier0 = (Supplier<Object>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn("GW5csb^").when(supplier0).get();
      Object object0 = commandLine0.getParsedOptionValue("GW5csb^", (Supplier<Object>) supplier0);
      assertEquals("GW5csb^", object0);
  }

  @Test(timeout = 4000)
  public void test023()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object object0 = commandLine0.getParsedOptionValue("org.apache.commons.io.file.CountingPathVisitor$Builder", (Object) null);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test024()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder("options");
      Option.Builder option_Builder1 = option_Builder0.numberOfArgs(2014);
      Option option0 = option_Builder1.get();
      option0.processValue("options");
      commandLine0.addOption(option0);
      String string0 = commandLine0.getParsedOptionValue("options");
      assertEquals("options", string0);
  }

  @Test(timeout = 4000)
  public void test025()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<Object> supplier0 = (Supplier<Object>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Object object0 = commandLine0.getParsedOptionValue('i', (Supplier<Object>) supplier0);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test026()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object object0 = commandLine0.getParsedOptionValue('5', (Object) null);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test027()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("initialBuffer", "L!ok");
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder1.get();
      Option[] optionArray0 = commandLine0.getOptions();
      assertEquals(1, optionArray0.length);
  }

  @Test(timeout = 4000)
  public void test028()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Option.Builder option_Builder0 = Option.builder("options");
      Option.Builder option_Builder1 = option_Builder0.numberOfArgs(2014);
      Option option0 = option_Builder1.get();
      optionGroup0.setSelected(option0);
      option0.processValue("r_");
      commandLine0.addOption(option0);
      String[] stringArray0 = commandLine0.getOptionValues(optionGroup0);
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test029()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("r_", "r_", true, "r_");
      option0.processValue("r_");
      commandLine0.addOption(option0);
      String[] stringArray0 = commandLine0.getOptionValues("r_");
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test030()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      char[] charArray0 = new char[2];
      TextStringBuilder textStringBuilder0 = TextStringBuilder.wrap(charArray0);
      String string0 = commandLine0.getOptionValue((OptionGroup) null, (Supplier<String>) textStringBuilder0);
      assertEquals("\u0000\u0000", string0);
  }

  @Test(timeout = 4000)
  public void test031()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder((-617));
      String string0 = commandLine0.getOptionValue(optionGroup0, (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test032()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getOptionValue(optionGroup0, (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test033()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getOptionValue(optionGroup0, "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test034()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder((-1955));
      String string0 = commandLine0.getOptionValue((Option) null, (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test035()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, false, (String) null);
      String string0 = commandLine0.getOptionValue(option0, (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test036()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("r_", "r_", true, "r_");
      option0.processValue("r_");
      commandLine0.addOption(option0);
      String string0 = commandLine0.getOptionValue(option0);
      assertEquals("r_", string0);
  }

  @Test(timeout = 4000)
  public void test037()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      char[] charArray0 = new char[7];
      TextStringBuilder textStringBuilder0 = TextStringBuilder.wrap(charArray0, 5);
      String string0 = commandLine0.getOptionValue("true", (Supplier<String>) textStringBuilder0);
      assertEquals("\u0000\u0000\u0000\u0000\u0000", string0);
  }

  @Test(timeout = 4000)
  public void test038()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder(0);
      String string0 = commandLine0.getOptionValue("", (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test039()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue((String) null, (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test040()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue((String) null, "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test041()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("r_", "r_", true, "r_");
      option0.processValue("org.apache.commons.cli.Option$1");
      commandLine0.addOption(option0);
      String string0 = commandLine0.getOptionValue("r_");
      assertEquals("org.apache.commons.cli.Option$1", string0);
  }

  @Test(timeout = 4000)
  public void test042()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue('$', (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test043()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder("");
      String string0 = commandLine0.getOptionValue('5', (Supplier<String>) textStringBuilder0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test044()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue('^', "Km");
      assertEquals("Km", string0);
  }

  @Test(timeout = 4000)
  public void test045()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue('\\', "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test046()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("o", "o", true, "o");
      option0.processValue("o");
      commandLine0.addOption(option0);
      Properties properties0 = commandLine0.getOptionProperties(option0);
      assertFalse(properties0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test047()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("r_", "r_", true, "r_");
      option0.processValue("r_");
      commandLine0.addOption(option0);
      Object object0 = commandLine0.getOptionObject("r_");
      assertEquals("r_", object0);
  }

  @Test(timeout = 4000)
  public void test048()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("o", "o", true, "o");
      option0.processValue("o");
      commandLine0.addOption(option0);
      Object object0 = commandLine0.getOptionObject('o');
      assertEquals("o", object0);
  }

  @Test(timeout = 4000)
  public void test049()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("$", "$", true, "");
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder1.get();
      int int0 = commandLine0.getOptionCount(option0);
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test050()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("initialBuffer", "L!ok");
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder1.get();
      int int0 = commandLine0.getOptionCount("initialBuffer");
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test051()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addArg("K]96xCBUl^.WnG");
      CommandLine commandLine0 = commandLine_Builder1.get();
      String[] stringArray0 = commandLine0.getArgs();
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test052()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      commandLine_Builder0.addArg("q1qaiFh2lMLq");
      List<String> list0 = commandLine0.getArgList();
      assertTrue(list0.contains("q1qaiFh2lMLq"));
  }

  @Test(timeout = 4000)
  public void test053()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option((String) null, "", false, "I3ayF8-gA!a2d");
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option.Builder option_Builder0 = Option.builder((String) null);
      try { 
        commandLine0.getParsedOptionValue(option0, (Supplier<Option>) option_Builder0);
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // org.evosuite.runtime.mock.java.lang.MockThrowable: Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.ParseException", e);
      }
  }

  @Test(timeout = 4000)
  public void test054()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        commandLine0.getParsedOptionValue((Option) null, (Supplier<Option>) option_Builder0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test055()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        commandLine0.getParsedOptionValue('n', (Supplier<Option>) option_Builder0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test056()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("3g4W", "3g4W", true, "3g4W");
      boolean boolean0 = commandLine0.hasOption(option0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test057()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option("after", (String) null);
      optionGroup0.setSelected(option0);
      Supplier<Integer[]> supplier0 = (Supplier<Integer[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Integer[] integerArray0 = commandLine0.getParsedOptionValues(optionGroup0, (Supplier<Integer[]>) supplier0);
      assertNull(integerArray0);
  }

  @Test(timeout = 4000)
  public void test058()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Integer[] integerArray0 = new Integer[2];
      Supplier<Integer[]> supplier0 = (Supplier<Integer[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(integerArray0).when(supplier0).get();
      Integer[] integerArray1 = commandLine0.getParsedOptionValues(optionGroup0, (Supplier<Integer[]>) supplier0);
      assertSame(integerArray1, integerArray0);
  }

  @Test(timeout = 4000)
  public void test059()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Integer[] integerArray0 = commandLine0.getParsedOptionValues((OptionGroup) null, (Supplier<Integer[]>) null);
      assertNull(integerArray0);
  }

  @Test(timeout = 4000)
  public void test060()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder("options");
      Option.Builder option_Builder1 = option_Builder0.numberOfArgs(2014);
      Option option0 = option_Builder1.get();
      option0.processValue("org.apache.commons.cli.Option$1");
      commandLine0.addOption(option0);
      Supplier<String[]> supplier0 = (Supplier<String[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      String[] stringArray0 = commandLine0.getParsedOptionValues(option0, (Supplier<String[]>) supplier0);
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test061()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<Integer[]> supplier0 = (Supplier<Integer[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Integer[] integerArray0 = commandLine0.getParsedOptionValues((Option) null, (Supplier<Integer[]>) supplier0);
      assertNull(integerArray0);
  }

  @Test(timeout = 4000)
  public void test062()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      char[] charArray0 = new char[2];
      TextStringBuilder textStringBuilder0 = TextStringBuilder.wrap(charArray0);
      String string0 = commandLine0.getParsedOptionValue((OptionGroup) null, (Supplier<String>) textStringBuilder0);
      assertEquals("\u0000\u0000", string0);
  }

  @Test(timeout = 4000)
  public void test063()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, "oM[MR3", true, "options");
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      Supplier<Integer> supplier0 = (Supplier<Integer>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((-1)).when(supplier0).get();
      Integer integer0 = commandLine0.getParsedOptionValue(optionGroup0, (Supplier<Integer>) supplier0);
      assertEquals((-1), (int)integer0);
  }

  @Test(timeout = 4000)
  public void test064()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder("options");
      Option.Builder option_Builder1 = option_Builder0.numberOfArgs(2014);
      Option option0 = option_Builder1.get();
      option0.processValue("org.apache.commons.cli.Option$1");
      commandLine0.addOption(option0);
      TextStringBuilder textStringBuilder0 = new TextStringBuilder();
      String string0 = commandLine0.getParsedOptionValue(option0, (Supplier<String>) textStringBuilder0);
      assertEquals("org.apache.commons.cli.Option$1", string0);
  }

  @Test(timeout = 4000)
  public void test065()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      String[] stringArray0 = commandLine0.getOptionValues(optionGroup0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test066()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("r_", "r_", true, "r_");
      option0.processValue("org.apache.commons.cli.Option$1");
      commandLine0.addOption(option0);
      String[] stringArray0 = commandLine0.getOptionValues(option0);
      assertEquals(1, stringArray0.length);
  }

  @Test(timeout = 4000)
  public void test067()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String[] stringArray0 = commandLine0.getOptionValues((Option) null);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test068()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, (String) null);
      String[] stringArray0 = commandLine0.getOptionValues(option0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test069()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("r_", "r_", true, "r_");
      option0.processValue("r_");
      commandLine0.addOption(option0);
      TextStringBuilder textStringBuilder0 = new TextStringBuilder((CharSequence) "r_");
      String string0 = commandLine0.getOptionValue(option0, (Supplier<String>) textStringBuilder0);
      assertEquals("r_", string0);
  }

  @Test(timeout = 4000)
  public void test070()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("3g4W", true, "3g4W");
      String string0 = commandLine0.getOptionValue(option0, (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test071()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("options", "\"m{be#ui :", false, "options");
      TextStyle[] textStyleArray0 = new TextStyle[5];
      TextStyle[] textStyleArray1 = commandLine0.getParsedOptionValues(option0, textStyleArray0);
      assertEquals(5, textStyleArray1.length);
  }

  @Test(timeout = 4000)
  public void test072()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      int int0 = commandLine0.getOptionCount("%Bc");
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test073()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getOptionValue(optionGroup0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test074()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Supplier<LinkedList<LinkedList>[]> supplier0 = (Supplier<LinkedList<LinkedList>[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      LinkedList<LinkedList>[] linkedListArray0 = commandLine0.getParsedOptionValues("lq#76Z2'vf'$Y", supplier0);
      assertNull(linkedListArray0);
  }

  @Test(timeout = 4000)
  public void test075()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Locale.FilteringMode[] locale_FilteringModeArray0 = new Locale.FilteringMode[4];
      Locale.FilteringMode[] locale_FilteringModeArray1 = commandLine0.getParsedOptionValues("", locale_FilteringModeArray0);
      assertEquals(4, locale_FilteringModeArray1.length);
  }

  @Test(timeout = 4000)
  public void test076()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        commandLine0.getParsedOptionValue("+", (Supplier<Option>) option_Builder0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test077()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object[] objectArray0 = commandLine0.getParsedOptionValues("");
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test078()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = commandLine0.getOptionValues((String) null);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test079()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Integer integer0 = commandLine0.getParsedOptionValue((Option) null);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test080()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue("J6|b}(t", (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test081()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object object0 = commandLine0.getOptionObject("6no-.cB");
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test082()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option((String) null, (String) null);
      String string0 = commandLine0.getOptionValue(option0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test083()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Integer integer0 = commandLine0.getParsedOptionValue("$di\"9O]|y>hD I");
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test084()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      boolean boolean0 = commandLine0.hasOption((String) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test085()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("r_", "r_", true, "r_");
      option0.processValue("org.apache.commons.cli.Option$1");
      commandLine0.addOption(option0);
      Properties properties0 = commandLine0.getOptionProperties("r_");
      assertEquals(1, properties0.size());
  }

  @Test(timeout = 4000)
  public void test086()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("r_", "r_", true, "r_");
      commandLine0.addOption(option0);
      Properties properties0 = commandLine0.getOptionProperties("r_");
      assertTrue(properties0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test087()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Option.Builder option_Builder0 = Option.builder("oq");
      Option option0 = option_Builder0.get();
      optionGroup0.setSelected(option0);
      boolean boolean0 = commandLine0.hasOption(optionGroup0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test088()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      boolean boolean0 = commandLine0.hasOption(optionGroup0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test089()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      boolean boolean0 = commandLine0.hasOption((OptionGroup) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test090()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("initialBuffer", "L!ok");
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder1.get();
      Option.Builder option_Builder0 = Option.builder("initialBuffer");
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      option_Builder0.deprecated(deprecatedAttributes0);
      Option option1 = option_Builder0.get();
      boolean boolean0 = commandLine0.hasOption(option1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test091()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("initialBuffer", "L!ok");
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder1.get();
      boolean boolean0 = commandLine0.hasOption(option0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test092()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      Option option0 = new Option("initialBuffer", "L!ok");
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder1.get();
      String[] stringArray0 = commandLine0.getArgs();
      Option.Builder option_Builder0 = Option.builder("initialBuffer");
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      Option.Builder option_Builder1 = option_Builder0.deprecated(deprecatedAttributes0);
      Option option1 = option_Builder1.get();
      Supplier<Object[]> supplier0 = (Supplier<Object[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(supplier0).get();
      Object[] objectArray0 = commandLine0.getParsedOptionValues(option1, (Supplier<Object[]>) supplier0);
      assertEquals(0, objectArray0.length);
  }

  @Test(timeout = 4000)
  public void test093()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.setDeprecatedHandler((Consumer<Option>) null);
      Option option0 = new Option("initialBuffer", "K]96xCBUl^.WnG");
      CommandLine.Builder commandLine_Builder2 = commandLine_Builder1.addOption(option0);
      CommandLine commandLine0 = commandLine_Builder2.get();
      String[] stringArray0 = commandLine0.getArgs();
      Option.Builder option_Builder0 = Option.builder("initialBuffer");
      DeprecatedAttributes deprecatedAttributes0 = DeprecatedAttributes.DEFAULT;
      Option.Builder option_Builder1 = option_Builder0.deprecated(deprecatedAttributes0);
      Option option1 = option_Builder1.get();
      Supplier<Object[]> supplier0 = (Supplier<Object[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(stringArray0).when(supplier0).get();
      Object[] objectArray0 = commandLine0.getParsedOptionValues(option1, (Supplier<Object[]>) supplier0);
      assertSame(stringArray0, objectArray0);
  }

  @Test(timeout = 4000)
  public void test094()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Option option0 = new Option("after", (String) null);
      optionGroup0.setSelected(option0);
      String[] stringArray0 = commandLine0.getParsedOptionValues(optionGroup0);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test095()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder("options");
      Option.Builder option_Builder1 = option_Builder0.numberOfArgs(2014);
      Option option0 = option_Builder1.get();
      option0.processValue("org.apache.commons.cli.Option$1");
      commandLine0.addOption(option0);
      Object[] objectArray0 = commandLine0.getParsedOptionValues(option0);
      assertEquals(1, objectArray0.length);
  }

  @Test(timeout = 4000)
  public void test096()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder("options");
      Option option0 = option_Builder0.get();
      Object[] objectArray0 = commandLine0.getParsedOptionValues(option0);
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test097()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("U", "U");
      OptionGroup optionGroup0 = new OptionGroup();
      optionGroup0.setSelected(option0);
      LinkedList<String> linkedList0 = commandLine0.getParsedOptionValue(optionGroup0);
      assertNull(linkedList0);
  }

  @Test(timeout = 4000)
  public void test098()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      Option.Builder option_Builder0 = Option.builder();
      // Undeclared exception!
      try { 
        commandLine0.getParsedOptionValue(optionGroup0, (Supplier<Option>) option_Builder0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Either opt or longOpt must be specified
         //
         verifyException("org.apache.commons.cli.Option", e);
      }
  }

  @Test(timeout = 4000)
  public void test099()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = commandLine0.getOptionValues((OptionGroup) null);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test100()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option option0 = new Option("r_", "r_", true, "r_");
      option0.processValue("r_");
      commandLine0.addOption(option0);
      String string0 = commandLine0.getOptionValue(option0, "");
      assertEquals("r_", string0);
  }

  @Test(timeout = 4000)
  public void test101()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getOptionValue(optionGroup0, (Supplier<String>) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test102()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder("options");
      Option.Builder option_Builder1 = option_Builder0.numberOfArgs(2014);
      Option option0 = option_Builder1.get();
      option0.processValue("org.apache.commons.cli.Option$1");
      commandLine0.addOption(option0);
      String string0 = commandLine0.getParsedOptionValue(option0, "yN<j");
      assertEquals("org.apache.commons.cli.Option$1", string0);
  }

  @Test(timeout = 4000)
  public void test103()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder("options");
      Option option0 = option_Builder0.get();
      commandLine0.addOption(option0);
      // Undeclared exception!
      try { 
        commandLine0.getOptionProperties((String) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
      }
  }

  @Test(timeout = 4000)
  public void test104()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      commandLine0.addOption((Option) null);
  }

  @Test(timeout = 4000)
  public void test105()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      commandLine0.addArg("");
  }

  @Test(timeout = 4000)
  public void test106()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      commandLine0.addArg((String) null);
  }

  @Test(timeout = 4000)
  public void test107()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addOption((Option) null);
      assertSame(commandLine_Builder1, commandLine_Builder0);
  }

  @Test(timeout = 4000)
  public void test108()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine.Builder commandLine_Builder1 = commandLine_Builder0.addArg((String) null);
      assertSame(commandLine_Builder1, commandLine_Builder0);
  }

  @Test(timeout = 4000)
  public void test109()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Integer integer0 = commandLine0.getParsedOptionValue((OptionGroup) null, (Integer) null);
      assertNull(integer0);
  }

  @Test(timeout = 4000)
  public void test110()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = commandLine0.getOptionValues('M');
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test111()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue("Minimum code point %d is negative", "Minimum code point %d is negative");
      assertEquals("Minimum code point %d is negative", string0);
  }

  @Test(timeout = 4000)
  public void test112()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option[] optionArray0 = commandLine0.getOptions();
      OptionGroup optionGroup0 = new OptionGroup();
      Supplier<Object[]> supplier0 = (Supplier<Object[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Object[] objectArray0 = commandLine0.getParsedOptionValues(optionGroup0, (Supplier<Object[]>) supplier0);
      assertSame(optionArray0, objectArray0);
  }

  @Test(timeout = 4000)
  public void test113()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      List<String> list0 = commandLine0.getArgList();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test114()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      OptionGroup optionGroup0 = new OptionGroup();
      String string0 = commandLine0.getOptionValue(optionGroup0, "U");
      assertEquals("U", string0);
  }

  @Test(timeout = 4000)
  public void test115()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder("options");
      Option option0 = option_Builder0.get();
      String string0 = commandLine0.getOptionValue(option0, "");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test116()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      boolean boolean0 = commandLine0.hasOption('3');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test117()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Object[] objectArray0 = commandLine0.getParsedOptionValues((OptionGroup) null, (Object[]) null);
      assertNull(objectArray0);
  }

  @Test(timeout = 4000)
  public void test118()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue('M');
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test119()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Option.Builder option_Builder0 = Option.builder("options");
      Option option0 = option_Builder0.get();
      Properties properties0 = commandLine0.getOptionProperties(option0);
      assertTrue(properties0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test120()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Object object0 = commandLine0.getOptionObject('x');
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test121()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Integer[] integerArray0 = commandLine0.getParsedOptionValues('!');
      assertNull(integerArray0);
  }

  @Test(timeout = 4000)
  public void test122()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      int int0 = commandLine0.getOptionCount('x');
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test123()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      TextStringBuilder textStringBuilder0 = new TextStringBuilder("U");
      String string0 = commandLine0.getOptionValue('G', (Supplier<String>) textStringBuilder0);
      assertEquals("U", string0);
  }

  @Test(timeout = 4000)
  public void test124()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      LinkedList<String> linkedList1 = commandLine0.getParsedOptionValue('T', linkedList0);
      assertSame(linkedList1, linkedList0);
  }

  @Test(timeout = 4000)
  public void test125()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String string0 = commandLine0.getOptionValue('x', (String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test126()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Iterator<Option> iterator0 = commandLine0.iterator();
      assertNotNull(iterator0);
  }

  @Test(timeout = 4000)
  public void test127()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      Integer integer0 = new Integer(649);
      Supplier<Integer> supplier0 = (Supplier<Integer>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn(integer0).when(supplier0).get();
      Integer integer1 = commandLine0.getParsedOptionValue('9', (Supplier<Integer>) supplier0);
      assertEquals(649, (int)integer1);
  }

  @Test(timeout = 4000)
  public void test128()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      Supplier<Integer[]> supplier0 = (Supplier<Integer[]>) mock(Supplier.class, new ViolatedAssumptionAnswer());
      doReturn((Object) null).when(supplier0).get();
      Integer[] integerArray0 = commandLine0.getParsedOptionValues('x', (Supplier<Integer[]>) supplier0);
      assertNull(integerArray0);
  }

  @Test(timeout = 4000)
  public void test129()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      int int0 = commandLine0.getOptionCount((Option) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test130()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      commandLine0.getParsedOptionValue('m');
  }

  @Test(timeout = 4000)
  public void test131()  throws Throwable  {
      CommandLine commandLine0 = new CommandLine();
      String[] stringArray0 = commandLine0.getParsedOptionValues('!', (String[]) null);
      assertNull(stringArray0);
  }

  @Test(timeout = 4000)
  public void test132()  throws Throwable  {
      CommandLine.Builder commandLine_Builder0 = CommandLine.builder();
      CommandLine commandLine0 = commandLine_Builder0.get();
      String string0 = commandLine0.getOptionValue("");
      assertNull(string0);
  }
}
