/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 14 21:21:48 GMT 2026
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.apache.commons.cli.GnuParser;
import org.apache.commons.cli.Options;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class GnuParser_ESTest extends GnuParser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      GnuParser gnuParser0 = new GnuParser();
      String[] stringArray0 = new String[4];
      stringArray0[0] = "-6\"8";
      // Undeclared exception!
      try { 
        gnuParser0.flatten((Options) null, stringArray0, true);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.apache.commons.cli.GnuParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      GnuParser gnuParser0 = new GnuParser();
      Options options0 = new Options();
      String[] stringArray0 = new String[26];
      Boolean boolean0 = Boolean.TRUE;
      options0.addRequiredOption("v", "--v=`=Gt+7eHpm nb>?|", (boolean) boolean0, "v");
      stringArray0[23] = "-v]=GNt+7eHpm^?@";
      String[] stringArray1 = gnuParser0.flatten(options0, stringArray0, (boolean) boolean0);
      assertEquals(2, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      GnuParser gnuParser0 = new GnuParser();
      Options options0 = new Options();
      String[] stringArray0 = new String[26];
      stringArray0[3] = "--v=`=Gt+7eHpm nb>?|";
      Boolean boolean0 = Boolean.TRUE;
      String[] stringArray1 = gnuParser0.flatten(options0, stringArray0, (boolean) boolean0);
      assertEquals(23, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      GnuParser gnuParser0 = new GnuParser();
      Options options0 = new Options();
      String[] stringArray0 = new String[26];
      stringArray0[3] = "--v=`=Gt+7eHpm nb>?|";
      Boolean boolean0 = Boolean.TRUE;
      options0.addRequiredOption("v", "--v=`=Gt+7eHpm nb>?|", (boolean) boolean0, "v");
      String[] stringArray1 = gnuParser0.flatten(options0, stringArray0, (boolean) boolean0);
      String[] stringArray2 = gnuParser0.flatten(options0, stringArray1, (boolean) boolean0);
      assertEquals(2, stringArray2.length);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      GnuParser gnuParser0 = new GnuParser();
      String[] stringArray0 = new String[16];
      stringArray0[6] = "-";
      String[] stringArray1 = gnuParser0.flatten((Options) null, stringArray0, true);
      assertEquals(1, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Options options0 = new Options();
      String[] stringArray0 = new String[11];
      stringArray0[0] = "-,";
      GnuParser gnuParser0 = new GnuParser();
      String[] stringArray1 = gnuParser0.flatten(options0, stringArray0, true);
      assertEquals(11, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      GnuParser gnuParser0 = new GnuParser();
      String[] stringArray0 = new String[25];
      stringArray0[1] = "--";
      String[] stringArray1 = gnuParser0.flatten((Options) null, stringArray0, false);
      assertEquals(24, stringArray1.length);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      GnuParser gnuParser0 = new GnuParser();
      String[] stringArray0 = new String[25];
      String[] stringArray1 = gnuParser0.flatten((Options) null, stringArray0, false);
      assertEquals(0, stringArray1.length);
  }
}
