/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Sat Mar 14 21:32:49 GMT 2026
 */

package org.apache.commons.cli;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class TypeHandler_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.commons.cli.TypeHandler"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/jx/mmlj34wd62vbjkzchbls8tgw0000gn/T/"); 
    java.lang.System.setProperty("user.country", "CA"); 
    java.lang.System.setProperty("user.dir", "/Users/kietvandang/Projects/EECS4313/commons-cli"); 
    java.lang.System.setProperty("user.home", "/Users/kietvandang"); 
    java.lang.System.setProperty("user.language", "en"); 
    java.lang.System.setProperty("user.name", "kietvandang"); 
    java.lang.System.setProperty("user.timezone", "America/Toronto"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(TypeHandler_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.commons.cli.example.WeirdOptionFormat",
      "org.apache.commons.io.FileSystem$NameLengthStrategy",
      "org.apache.commons.io.serialization.ClassNameMatcher",
      "org.apache.commons.io.serialization.WildcardClassNameMatcher",
      "org.apache.commons.cli.help.TextStyle$Builder",
      "org.apache.commons.cli.TypeHandler",
      "org.apache.commons.cli.help.TextStyle$Alignment",
      "org.apache.commons.cli.help.TableDefinition",
      "org.apache.commons.cli.Converter",
      "org.apache.commons.io.file.AccumulatorPathVisitor$1",
      "org.apache.commons.cli.ParseException",
      "org.apache.commons.io.FileSystem$NameLengthStrategy$1",
      "org.apache.commons.cli.help.TextStyle",
      "org.apache.commons.io.FileSystem$NameLengthStrategy$2",
      "net.bytebuddy.description.NamedElement"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(TypeHandler_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.commons.cli.Converter",
      "org.apache.commons.cli.TypeHandler",
      "net.bytebuddy.build.HashCodeAndEqualsPlugin$Enhance$InvokeSuper",
      "org.apache.commons.io.file.AccumulatorPathVisitor$1",
      "org.apache.commons.cli.ParseException",
      "org.apache.commons.io.serialization.WildcardClassNameMatcher",
      "org.apache.commons.cli.example.WeirdOptionFormat",
      "org.apache.commons.cli.help.TextStyle$Builder",
      "org.apache.commons.cli.help.TextStyle$Alignment",
      "org.apache.commons.cli.help.TextStyle",
      "org.apache.commons.text.similarity.CosineDistance",
      "org.junitpioneer.jupiter.cartesian.CartesianFactoryArgumentsProvider",
      "org.hsqldb.jdbc.JDBCDriver",
      "org.apache.commons.io.build.AbstractSupplier",
      "org.apache.commons.io.file.SimplePathVisitor$AbstractBuilder",
      "org.apache.commons.io.file.Counters$NoopCounter",
      "org.apache.commons.io.filefilter.IOFileFilter",
      "org.apache.commons.io.filefilter.AbstractFileFilter",
      "org.apache.commons.io.filefilter.SuffixFileFilter",
      "org.junitpioneer.jupiter.json.AbstractJsonArgumentsProvider",
      "org.junitpioneer.jupiter.json.JsonInlineArgumentsProvider",
      "org.apache.commons.text.similarity.LongestCommonSubsequenceDistance",
      "org.apache.commons.io.filefilter.NotFileFilter",
      "org.apache.commons.io.filefilter.CanWriteFileFilter",
      "org.apache.commons.io.filefilter.AndFileFilter",
      "org.apache.commons.io.filefilter.CanReadFileFilter",
      "org.apache.commons.text.lookup.AbstractStringLookup",
      "org.apache.commons.text.lookup.AbstractPathFencedLookup",
      "org.apache.commons.text.lookup.PathFence",
      "org.apache.commons.text.lookup.PathFence$Builder",
      "org.apache.commons.text.lookup.FileStringLookup",
      "net.bytebuddy.description.NamedElement",
      "org.apache.commons.io.filefilter.TrueFileFilter",
      "org.apache.commons.text.similarity.LevenshteinDetailedDistance",
      "org.apache.commons.io.filefilter.FalseFileFilter",
      "org.apache.commons.io.filefilter.WildcardFileFilter$Builder",
      "org.apache.commons.io.FileSystem$NameLengthStrategy",
      "org.apache.commons.io.FilenameUtils",
      "org.apache.commons.io.FileSystem",
      "org.apache.commons.io.IOCase",
      "org.apache.commons.io.file.CountingPathVisitor$AbstractBuilder",
      "org.apache.commons.io.file.AccumulatorPathVisitor$Builder",
      "org.apache.commons.io.file.SimplePathVisitor",
      "org.apache.commons.io.file.CountingPathVisitor",
      "org.apache.commons.io.file.Counters",
      "org.apache.commons.io.file.Counters$AbstractPathCounters",
      "org.apache.commons.io.file.Counters$LongPathCounters",
      "org.apache.commons.io.file.Counters$LongCounter",
      "org.apache.commons.io.filefilter.SymbolicLinkFileFilter",
      "org.apache.commons.text.similarity.JaccardDistance",
      "org.apache.commons.io.filefilter.WildcardFilter",
      "org.apache.commons.io.filefilter.RegexFileFilter",
      "net.bytebuddy.dynamic.loading.InjectionClassLoader",
      "org.apache.commons.io.serialization.FullClassNameMatcher",
      "org.apache.commons.text.similarity.DamerauLevenshteinDistance",
      "org.apache.commons.io.filefilter.WildcardFileFilter",
      "org.apache.commons.text.lookup.XmlEncoderStringLookup",
      "org.junitpioneer.jupiter.json.AbstractJsonSourceBasedArgumentsProvider",
      "org.junitpioneer.jupiter.json.JsonFileSourceArgumentsProvider",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PackageLookupStrategy$CreationAction",
      "net.bytebuddy.utility.privilege.GetSystemPropertyAction",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$InvokerCreationAction",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$DynamicClassLoader",
      "net.bytebuddy.jar.asm.ClassVisitor",
      "net.bytebuddy.jar.asm.ClassWriter",
      "net.bytebuddy.jar.asm.SymbolTable",
      "net.bytebuddy.jar.asm.ByteVector",
      "net.bytebuddy.ClassFileVersion$VersionLocator$Resolver",
      "net.bytebuddy.ClassFileVersion$VersionLocator$Resolved",
      "net.bytebuddy.ClassFileVersion",
      "net.bytebuddy.jar.asm.Type",
      "net.bytebuddy.jar.asm.Symbol",
      "net.bytebuddy.jar.asm.SymbolTable$Entry",
      "net.bytebuddy.jar.asm.MethodVisitor",
      "net.bytebuddy.jar.asm.MethodWriter",
      "net.bytebuddy.jar.asm.Handler",
      "net.bytebuddy.jar.asm.Attribute",
      "net.bytebuddy.jar.asm.AnnotationVisitor",
      "net.bytebuddy.jar.asm.AnnotationWriter",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$Dispatcher$ForDefaultValue",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$ProxiedInvocationHandler",
      "net.bytebuddy.utility.dispatcher.JavaDispatcher$Dispatcher$ForUnresolvedMethod",
      "net.bytebuddy.utility.privilege.GetMethodAction",
      "net.bytebuddy.utility.JavaModule",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PackageLookupStrategy$ForLegacyVm",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$SynchronizationStrategy$CreationAction",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$SynchronizationStrategy$ForJava8CapableVm",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader",
      "net.bytebuddy.dynamic.loading.ByteArrayClassLoader$PersistenceHandler$UrlDefinitionAction",
      "org.junitpioneer.jupiter.CartesianValueArgumentsProvider",
      "org.apache.commons.text.lookup.UrlDecoderStringLookup",
      "org.apache.commons.text.lookup.DateStringLookup",
      "org.apache.commons.io.filefilter.PathMatcherFileFilter",
      "org.apache.commons.text.lookup.JavaPlatformStringLookup"
    );
  }
}
