/*
 * This file was automatically generated by EvoSuite
 * Sat Mar 14 21:32:49 GMT 2026
 */

package org.apache.commons.cli;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.File;
import java.net.URL;
import java.util.Map;
import org.apache.commons.cli.Converter;
import org.apache.commons.cli.TypeHandler;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TypeHandler_ESTest extends TypeHandler_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Object object0 = TypeHandler.createValue((String) null, (Object) null);
      assertNull(object0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Class<String> class0 = String.class;
      String string0 = TypeHandler.createValue((String) null, class0);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Class<String> class0 = String.class;
      String string0 = TypeHandler.createValue("", class0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      URL uRL0 = TypeHandler.createURL("http://javax.xml.XMLConstants/feature/secure-processing");
      assertEquals("http://javax.xml.XMLConstants/feature/secure-processing", uRL0.toExternalForm());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Object object0 = TypeHandler.createObject("org.apache.commons.cli.example.WeirdOptionFormat");
      assertNotNull(object0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Number number0 = TypeHandler.createNumber("2");
      assertEquals(2L, number0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Number number0 = TypeHandler.createNumber("-2");
      assertEquals((-2L), number0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      File file0 = TypeHandler.createFile("/8\"8x6N;u)njlA");
      assertEquals("8\"8x6N;u)njlA", file0.getName());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Class<Object> class0 = (Class<Object>)TypeHandler.createClass("org.apache.commons.io.file.AccumulatorPathVisitor$1");
      assertFalse(class0.isInterface());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Class<?> class0 = TypeHandler.createClass("net.bytebuddy.description.NamedElement");
      assertFalse(class0.isAnnotation());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Class<?> class0 = TypeHandler.createClass("org.apache.commons.io.FileSystem$NameLengthStrategy");
      assertFalse(class0.isPrimitive());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Class<Object> class0 = (Class<Object>)TypeHandler.createClass("org.apache.commons.io.serialization.WildcardClassNameMatcher");
      assertFalse(class0.isPrimitive());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      // Undeclared exception!
      try { 
        TypeHandler.createValue("=Xfi\"9D9?frQWXEf", (Object) "=Xfi\"9D9?frQWXEf");
        fail("Expecting exception: ClassCastException");
      
      } catch(ClassCastException e) {
         //
         // java.lang.String cannot be cast to java.lang.Class
         //
         verifyException("org.apache.commons.cli.TypeHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      try { 
        TypeHandler.createNumber("");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // java.lang.NumberFormatException: For input string: \"\"
         //
         verifyException("org.apache.commons.cli.ParseException", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      // Undeclared exception!
      try { 
        TypeHandler.createFile((String) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // org.evosuite.runtime.mock.java.lang.MockThrowable: java.lang.NullPointerException
         //
         verifyException("org.apache.commons.cli.TypeHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      try { 
        TypeHandler.createClass("H))dG6dFCDC");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // java.lang.ClassNotFoundException: Class 'H))dG6dFCDC.class' should be in target project, but could not be found!
         //
         verifyException("org.apache.commons.cli.ParseException", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TypeHandler typeHandler0 = null;
      try {
        typeHandler0 = new TypeHandler((Map<Class<?>, Converter<?, ? extends Throwable>>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // converterMap
         //
         verifyException("java.util.Objects", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      String string0 = "\\u";
      // Undeclared exception!
      try { 
        TypeHandler.createDate(string0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // org.evosuite.runtime.mock.java.lang.MockThrowable: java.text.ParseException: Unparseable date: \"\\u\"
         //
         verifyException("org.apache.commons.cli.TypeHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      try { 
        TypeHandler.createURL("0");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // java.net.MalformedURLException: no protocol: 0
         //
         verifyException("org.apache.commons.cli.ParseException", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Number number0 = TypeHandler.createNumber("0");
      assertEquals(0L, number0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      // Undeclared exception!
      try { 
        TypeHandler.createFiles("DocumentPath");
        fail("Expecting exception: UnsupportedOperationException");
      
      } catch(UnsupportedOperationException e) {
         //
         // Not yet implemented
         //
         verifyException("org.apache.commons.cli.TypeHandler", e);
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      try { 
        TypeHandler.openFile("[.RT");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // java.io.FileNotFoundException: [.RT (No such file or directory)
         //
         verifyException("org.apache.commons.cli.ParseException", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      String string0 = "\\u";
      Object object0 = TypeHandler.createValue(string0, (Object) null);
      assertEquals("\\u", object0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      try { 
        TypeHandler.createObject("org.apache.commons.io.file.AccumulatorPathVisitor$1");
        fail("Expecting exception: Exception");
      
      } catch(Exception e) {
         //
         // java.lang.NoSuchMethodException: org.apache.commons.io.file.AccumulatorPathVisitor$1.<init>()
         //
         verifyException("org.apache.commons.cli.ParseException", e);
      }
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      File file0 = TypeHandler.createFile(".class");
      assertEquals(".class", file0.getName());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      TypeHandler typeHandler0 = new TypeHandler();
  }
}
